"""New fields comment

Revision ID: 9cf801c70af2
Revises: 
Create Date: 2018-04-23 18:08:44.218454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf801c70af2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=128), nullable=False),
    sa.Column('author_email', sa.String(length=156), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sign_up_newsletter', sa.Boolean(), nullable=True),
    sa.Column('needs_moderation', sa.Boolean(), nullable=True),
    sa.Column('thread_id', sa.String(length=256), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
